name: Heavy Metal
favicon: null
layout_spectrum: 0.9181162312161177
typography_spectrum: 0.5335527225397527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.957480298820883
  lightness: 0.3985774184111506
  saturation: 0.5675906706601381
  rhythmicContrast: 0.5982807299587876
purpose: []
